version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  postgres:
    driver: local
  docker-in-docker:
    driver: local

services:

### Workspace Utilities ##################################
    workspace:
      build:
        context: ../.laradock/workspace
        args:
          - CHANGE_SOURCE=false
          - SHELL_OH_MY_ZSH=true
          - SHELL_OH_MY_ZSH_AUTOSUGESTIONS=true
          - SHELL_OH_MY_ZSH_ALIASES=false
          - UBUNTU_SOURCE=aliyun
          - BASE_IMAGE_TAG_PREFIX=latest
          - LARADOCK_PHP_VERSION=7.3
          - LARADOCK_PHALCON_VERSION=4.0.5
          - INSTALL_SUBVERSION=false
          - INSTALL_BZ2=false
          - INSTALL_GMP=false
          - INSTALL_XDEBUG=false
          - INSTALL_PCOV=false
          - INSTALL_PHPDBG=false
          - INSTALL_BLACKFIRE=false
          - INSTALL_SSH2=true
          - INSTALL_SOAP=true
          - INSTALL_XSL=true
          - INSTALL_LDAP=true
          - INSTALL_SMB=false
          - INSTALL_IMAP=false
          - INSTALL_MONGO=false
          - INSTALL_AMQP=false
          - INSTALL_CASSANDRA=false
          - INSTALL_GEARMAN=false
          - INSTALL_PHPREDIS=false
          - INSTALL_MSSQL=false
          - NVM_NODEJS_ORG_MIRROR=
          - INSTALL_NODE=true
          - NPM_REGISTRY=
          - INSTALL_PNPM=false
          - INSTALL_YARN=false
          - INSTALL_NPM_GULP=false
          - INSTALL_NPM_BOWER=false
          - INSTALL_NPM_VUE_CLI=false
          - INSTALL_NPM_ANGULAR_CLI=false
          - INSTALL_DRUSH=false
          - INSTALL_WP_CLI=false
          - INSTALL_DRUPAL_CONSOLE=false
          - INSTALL_AEROSPIKE=false
          - INSTALL_OCI8=false
          - INSTALL_V8JS=false
          - COMPOSER_GLOBAL_INSTALL=true
          - COMPOSER_AUTH=false
          - COMPOSER_REPO_PACKAGIST=
          - INSTALL_WORKSPACE_SSH=false
          - INSTALL_LARAVEL_ENVOY=false
          - INSTALL_LARAVEL_INSTALLER=false
          - INSTALL_DEPLOYER=false
          - INSTALL_PRESTISSIMO=false
          - INSTALL_LINUXBREW=false
          - INSTALL_MC=false
          - INSTALL_SYMFONY=false
          - INSTALL_PYTHON=false
          - INSTALL_PYTHON3=false
          - INSTALL_IMAGE_OPTIMIZERS=false
          - INSTALL_IMAGEMAGICK=false
          - INSTALL_TERRAFORM=false
          - INSTALL_DUSK_DEPS=false
          - INSTALL_PG_CLIENT=false
          - INSTALL_PHALCON=false
          - INSTALL_SWOOLE=false
          - INSTALL_TAINT=false
          - INSTALL_LIBPNG=false
          - INSTALL_GRAPHVIZ=false
          - INSTALL_IONCUBE=false
          - INSTALL_MYSQL_CLIENT=false
          - INSTALL_PING=true
          - INSTALL_SSHPASS=false
          - INSTALL_INOTIFY=false
          - INSTALL_FSWATCH=false
          - INSTALL_AST=false
          - INSTALL_YAML=true
          - INSTALL_RDKAFKA=false
          - INSTALL_MAILPARSE=false
          - INSTALL_GIT_PROMPT=false
          - INSTALL_XMLRPC=false
          - PUID=1000
          - PGID=1000
          - CHROME_DRIVER_VERSION=2.42
          - NODE_VERSION=node
          - YARN_VERSION=latest
          - DRUSH_VERSION=8.1.17
          - AST_VERSION=1.0.3
          - TZ=utc
          - BLACKFIRE_CLIENT_ID=<client_id>
          - BLACKFIRE_CLIENT_TOKEN=<client_token>
          - INSTALL_POWERLINE=false
          - INSTALL_SUPERVISOR=false
          - INSTALL_FFMPEG=false
          - INSTALL_WKHTMLTOPDF=false
          - INSTALL_GNU_PARALLEL=false
          - INSTALL_LNAV=false
          - INSTALL_PROTOC=false
          - PROTOC_VERSION=false
          - http_proxy
          - https_proxy
          - no_proxy
      volumes:
        - ../core/:/var/www:cached
        - docker-in-docker:/certs/client
      extra_hosts:
        - "dockerhost:10.0.75.1"
      ports:
        - "2222:22"
        - "3000:3000"
        - "3001:3001"
        - "8080:8080"
        - "8001:8000"
        - "4200:4200"
      tty: true
      environment:
        - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
        - DOCKER_HOST=tcp://docker-in-docker:2376
        - DOCKER_TLS_VERIFY=1
        - DOCKER_TLS_CERTDIR=/certs
        - DOCKER_CERT_PATH=/certs/client
      networks:
        - frontend
        - backend
      links:
        - docker-in-docker
            
### PHP-FPM ##############################################
    php-fpm:
      build:
        context: ../.laradock/php-fpm
        args:
          - CHANGE_SOURCE=false
          - BASE_IMAGE_TAG_PREFIX=latest
          - LARADOCK_PHP_VERSION=7.3
          - LARADOCK_PHALCON_VERSION=4.0.5
          - INSTALL_BZ2=false
          - INSTALL_GMP=false
          - INSTALL_XDEBUG=false
          - INSTALL_PCOV=false
          - INSTALL_PHPDBG=false
          - INSTALL_BLACKFIRE=false
          - INSTALL_SSH2=false
          - INSTALL_SOAP=false
          - INSTALL_XSL=false
          - INSTALL_SMB=false
          - INSTALL_IMAP=false
          - INSTALL_MONGO=false
          - INSTALL_AMQP=false
          - INSTALL_CASSANDRA=false
          - INSTALL_GEARMAN=false
          - INSTALL_MSSQL=false
          - INSTALL_BCMATH=false
          - INSTALL_PHPREDIS=false
          - INSTALL_MEMCACHED=false
          - INSTALL_OPCACHE=false
          - INSTALL_EXIF=false
          - INSTALL_AEROSPIKE=false
          - INSTALL_OCI8=false
          - INSTALL_MYSQLI=false
          - INSTALL_PGSQL=false
          - INSTALL_PG_CLIENT=false
          - INSTALL_POSTGIS=true
          - INSTALL_INTL=true
          - INSTALL_GHOSTSCRIPT=false
          - INSTALL_LDAP=false
          - INSTALL_PHALCON=false
          - INSTALL_SWOOLE=false
          - INSTALL_TAINT=false
          - INSTALL_IMAGE_OPTIMIZERS=false
          - INSTALL_IMAGEMAGICK=false
          - INSTALL_CALENDAR=false
          - INSTALL_FAKETIME=false
          - INSTALL_IONCUBE=false
          - INSTALL_APCU=false
          - INSTALL_CACHETOOL=false
          - INSTALL_YAML=true
          - INSTALL_RDKAFKA=false
          - INSTALL_GETTEXT=false
          - INSTALL_ADDITIONAL_LOCALES=false
          - INSTALL_MYSQL_CLIENT=false
          - INSTALL_PING=true
          - INSTALL_SSHPASS=false
          - INSTALL_MAILPARSE=false
          - INSTALL_PCNTL=false
          - ADDITIONAL_LOCALES="en_US.UTF-8 es_ES.UTF-8 fr_FR.UTF-8"
          - INSTALL_FFMPEG=false
          - INSTALL_WKHTMLTOPDF=false
          - INSTALL_XHPROF=false
          - INSTALL_XMLRPC=false
          - DOWNGRADE_OPENSSL_TLS_AND_SECLEVEL=false
          - PUID=1000
          - PGID=1000
          - LOCALE=POSIX
          - http_proxy
          - https_proxy
          - no_proxy
      volumes:
        - ../.laradock/php-fpm/php7.3.ini:/usr/local/etc/php/php.ini
        - ../core/:/var/www:cached
        - docker-in-docker:/certs/client
      expose:
        - "9000"
      extra_hosts:
        - "dockerhost:10.0.75.1"
      environment:
        - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
        - DOCKER_HOST=tcp://docker-in-docker:2376
        - DOCKER_TLS_VERIFY=1
        - DOCKER_TLS_CERTDIR=/certs
        - DOCKER_CERT_PATH=/certs/client
        - FAKETIME=-0
      depends_on:
        - workspace
      networks:
        - backend
      links:
        - docker-in-docker
### NGINX Server #########################################
    nginx:
      build:
        context: ../.laradock/nginx
        args:
          - CHANGE_SOURCE=false
          - NGINX_PHP_UPSTREAM_CONTAINER=php-fpm
          - NGINX_PHP_UPSTREAM_PORT=9000
          - http_proxy
          - https_proxy
          - no_proxy
      volumes:
        - ../core/:/var/www:cached
        - ./logs/nginx/:/var/log/nginx
        - ../.laradock/nginx/sites/:/etc/nginx/sites-available
        - ../.laradock/nginx/ssl/:/etc/nginx/ssl
      ports:
        - "80:80"
        - "443:443"
        - "81:81"
      depends_on:
        - php-fpm
      networks:
        - frontend
        - backend
### PostgreSQL ###########################################
    postgres:
      build:
        context: ../.laradock/postgres
        args:
          - POSTGRES_VERSION=alpine
      volumes:
        - ./data/PostgreSQL:/var/lib/postgresql/data
        - ../.laradock/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      networks:
        - backend
### Docker-in-Docker ################################################
    docker-in-docker:
      image: docker:19.03-dind
      environment:
        DOCKER_TLS_SAN: DNS:docker-in-docker      
      privileged: true
      volumes:
        - ../core/:/var/www
        - docker-in-docker:/certs/client
      expose:
        - 2375
      networks:
        - backend
### pgAdmin ##############################################
    pgadmin:
      image: dpage/pgadmin4:latest
      environment:
        - "PGADMIN_DEFAULT_EMAIL=test@test.com"
        - "PGADMIN_DEFAULT_PASSWORD=test"
      ports:
        - "5050:80"
      volumes:
        - ./data/pgadmin:/var/lib/pgadmin
      depends_on:
        - postgres
      networks:
        - frontend
        - backend